### ISSUE TITLE
Token Authentication things are missing?

### ISSUE THREAD

**Issue by isabasan** [blowdart/AspNetAuthorizationWorkshop#35]
It's really nice, clean and understandable work and thank you. But If the title is about Auth, I hope to see some works about token authentication.

**Comment by blowdart** [comment]
Well as we don't have an token issuers _yet_ I can't expand it. But soon, maybe, once 2.2 is out.

**Comment by ikourfaln** [comment]
@blowdart 
Thank you for the reply, but we really appreciate if you can share an example of using JWT Bearer authentication scheme instead of Cookies.
We are building applications using the ASP.NET Core and Angular, and we still looking for an official end2end example (Role, Claims, Policy) from you or in Microsoft docs.

**Comment by tonyaom** [comment]
Core 2.2 is just released, hopefully token authentication will be available

**Comment by blowdart** [comment]
It will follow as an OOB, and it's not going to be part of this workshop, as it's about authentication, not authorization.
